language: node_js
node_js:
  - "8"
install:
  - npm install    
after_success:
  - mkdir codedeploy
  - zip -r project-${TRAVIS_JOB_NUMBER}.zip *
notifications:
  email:
    recipients:
      - jia.xi@husky.neu.edu
    on_success: never # default: change
    on_failure: always # default: always   
  
