language: node_js
node_js:
  - "8"
install:
  - npm install

branches:
  only:
  - assignment6 

script:
  - pwd
  - ls
after_success:

notifications:
  email:
    recipients:
      - chen.zena@husky.neu.edu
    on_success: never # default: change
    on_failure: always # default: always   
  
