language: node_js
node_js:
  - "8"
install:
  - npm install

branches:
  only:
  - assignment6 

script:
  - pwd
  - ls
after_success:
  - mkdir codedeploy
  - zip -r csye6225-project-${TRAVIS_JOB_NUMBER}.zip * -x node_modules/\*
  - mv csye6225-project-${TRAVIS_JOB_NUMBER}.zip codedeploy/
  - ls 

notifications:
  email:
    recipients:
      - chen.zena@husky.neu.edu
    on_success: never # default: change
    on_failure: always # default: always   
  
