version: 0.0
os: linux

files:             
  - source: /
    destination: /home/ubuntu  

hooks:
  AfterInstall:
    - location: /scripts/npminstall.sh
      runas: root
      timeout: 1200
  ApplicationStart:
    - location: /scripts/startapplication.sh
      runas: root
      timeout: 1200    