language: node_js
node_js:
  - "8"
install:
  -npm install

sudo: false
install: true

branches:
  only:
  - $branch

after_success:
  - pwd
  - ls -al
  - mkdir codedeploy
  - zip -r csye6225-web-app-$TRAVIS_JOB_NUMBER.zip webapp/build/libs/ROOT.war infrastructure/aws/codedeploy/appspec.yml
  - ls -al
  - mv csye6225-web-app-$TRAVIS_JOB_NUMBER.zip codedeploy/
  - ls -al
  - pwd
  - cd codedeploy
  - ls -al
  - pwd
  - cd ..
  - pwd
  - ls -al

script:
  - pwd
  - cd webapp
  - ./gradlew war
  - cd ..
  - pwd
  - ls -al


